spring.application.name=customer-service

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/bankManagement_customer_db?createDatabaseIfNotExist=true

spring.config.import=optional:configserver:http://localhost:8084


